apiVersion: apps/v1
kind: Deployment
metadata:
    name: repair-deployment
    labels:
        app: hotelup
    namespace: hotelup
spec:
    replicas: 1
    selector:
        matchLabels:
            app: repair
    template:
        metadata:
            name: repair
            labels:
                app: repair
        spec:
            containers:
              - name: repair
                image: wiaz/hotelup.repair:latest
                imagePullPolicy: Always
                env:
                  - name: HOSTING_ENVIRONMENT
                    value: Production
                  - name: OAUTH2_CLIENT_ID
                    valueFrom:
                        secretKeyRef:
                            name: repair-secret
                            key: OAUTH2_CLIENT_ID
                  - name: OAUTH2_CLIENT_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: repair-secret
                            key: OAUTH2_CLIENT_SECRET
                  - name: OAUTH2_METADATA_URL
                    valueFrom:
                        secretKeyRef:
                            name: repair-secret
                            key: OAUTH2_METADATA_URL
                  - name: POSTGRES_DB
                    valueFrom:
                        secretKeyRef:
                            name: repair-secret
                            key: POSTGRES_DB
                  - name: RABBITMQ_HOST
                    value: rabbitmq-cluster
                ports:
                  - containerPort: 5001
                    protocol: TCP
            restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: repair-service
    labels:
        app: repair
    namespace: hotelup
spec:
    selector:
        app: repair
    ports:
      - protocol: TCP
        port: 5001
        targetPort: 5001
    type: ClusterIP
