name: Dockerhub
on:
    push:
        branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 8.0.x
            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --no-restore
            -   name: Unit tests
                run: dotnet test Tests/HotelUp.Employee.Tests.Unit --no-build --verbosity normal
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build and push multi-arch images
                uses: docker/build-push-action@v6
                with:
                    push: true
                    platforms: linux/amd64,linux/arm64
                    tags: wiaz/hotelup.employee:latest
